### ISSUE TITLE
Multi-line text.? 

### ISSUE THREAD

**Issue by mboveiri** [unlocomqx/text-measure#1]
Hi.
how to use the result when i want to draw multi-line texts.?

**Comment by unlocomqx** [comment]
Hi, 

It works out of the box, here's a preview
![image](https://user-images.githubusercontent.com/793712/29220070-475723d0-7eba-11e7-8a92-7acfec9c01e4.png)
Link to preview:
.../index.php?text=Hello%0AWorld!
